### PR TITLE
Improve Chinese translations

### PR DESCRIPTION
**Pull request by max-hk**
I am a native Chinese speaker in Hong Kong and would like to help improving Chinese translations for the project.

Most updated wordings comes from [Chinese Microsoft docs](https://docs.microsoft.com/zh-tw) or official Chinese translation for Windows.

I got a few questions though,

- Does `fragment.timestamp` mean `release date`?
- Does `button.website` mean `official website` or `git repository`?

I would try to update some inaccurate translation for zh-CN too.

### CODE REVIEW

**Comment by spikespaz** [comment]
`fragment.timestamp` means the date that the release file was uploaded to GitHub. I suppose that "release date" would be the closest thing, yes.

`button.website` does mean "Official Website" however it is currently just the GitHub page. I named the button to be generic so that I can update it with a link to a future website that I may or may not create.

**Review by spikespaz — CHANGES_REQUESTED** [review]
Needed removal of "Currently there is only one"

**Comment by max-hk** [comment]
One last question, Microsoft rarely use the word "preferred" in Windows, so I have trouble translating the word. To translate the phrase "Preferred Browser" and "Preferred Search Engine", I can think of two options, `Configure Browser`/`Configure Search Engine` or just `Browser`/`Search Engine`. Which options do you prefer?

I will review all the wordings one more time tomorrow. After that, the pull request will be ready to merge :)

**Comment by max-hk** [comment]
> One last question, Microsoft rarely use the word "preferred" in Windows, so I have trouble translating the word. To translate the phrase "Preferred Browser" and "Preferred Search Engine", I can think of two options, `Configure Browser`/`Configure Search Engine` or just `Browser`/`Search Engine`. Which options do you prefer?
> 
> I will review all the wordings one more time tomorrow. After that, the pull request will be ready to merge :)

@spikespaz Still waiting for your answer. The pull request is ready for review.

**Comment by spikespaz** [comment]
Apologies for the delay, I'm currently on break at my job. Open source software doesn't pay well unfortunately.

Just pick whichever one you like best, they are your translations and I'm not sure what you would use in Chinese. I would use alternative terms like "favorite" or "chosen" but I don't know how that would translate and what would be most proper. Thanks for doing this!

**Review by spikespaz — COMMENTED** [review]
I can't read this, but I'm going to assume it's alright! Thanks @maxloh!

**Pull request merged**
